### ISSUE TITLE
Sub System apx_managed code 256?

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/vanilla-control-center#101]
OS: VanillaOS 22.10 all (64-bit)
CPU: AMD Ryzen 3 3200G
Gnome Version: 43.1
Window system: Wayland

When trying to start up the sub system I get the following error:

```
Container apx_managed is not running.
Starting container apx_managed
run this command to follow along:

 podman logs -f apx_managed

Error: OCI runtime error: unable to start container "8900f77e1bfb98e57473d8270e1bbe7e56999a02ac2353eb60036d4bdf9e0cbb": mount `/etc/localtime` to `/etc/localtime`: Not a directory
⌬ Apx :: Failed to enter container: exit status 125

Read Only - command exited with code 256
```

**Comment by mirkobrombin** [comment]
Try initializing it from console: apx init

**Comment by ghost** [comment]
That worked. I think i'm opt in for crash reports, but does it cover some sections of the OS such as that? Where can I pull up logs to submit to the developers?

**Comment by mirkobrombin** [comment]
There are no useful logs sadly. I am pretty sure the bug is in Apx, I'll check it later

**Comment by lud3ns** [comment]
Yesterday I had this same issue on apx_managed, apx_managed_aur, apx_managed_dnf

Just a few hours after a fresh install of Vanilla, started happening again but limited to apx_managed_dnf
Was too busy to really do much with the system before this started, so the only thing I'd done on the system was install Discord via software center.

![image](https://user-images.githubusercontent.com/123912076/215367815-53321655-5782-429a-879a-a7824da8c7fd.png)

**Comment by lud3ns** [comment]
Update:
Ran `podman rm apx_managed_dnf`

After this, changed and changed back my time/date via gnome settings.

ran `apx --dnf init` and container was created successfully without the error.

Hope this helps in some way- I know literally nothing about Linux, but this worked.
I'm sure someone experienced can figure out why.

![image](https://user-images.githubusercontent.com/123912076/215375917-e428f748-2ed1-45cf-9d53-d0ce3c66c042.png)

**Comment by mirkobrombin** [comment]
Maybe it couldn't communicate with the server for downloading the image, because the pc time was wrong.

**Comment by mirkobrombin** [comment]
merging with https://github.com/Vanilla-OS/apx/issues/97 (also wrong repo)
