### ISSUE TITLE
Low contrast icon

### ISSUE THREAD

**Issue by TheEvilSkeleton** [Vanilla-OS/vanilla-control-center#102]
Yellow on white does not work well because it has low contrast.

 ![](https://github.com/Vanilla-OS/vanilla-control-center/raw/main/data/icons/hicolor/scalable/apps/org.vanillaos.ControlCenter.svg)

Instead, yellow should be a color that does not cause it to be low contrast.

**Comment by kbdharun** [comment]
VCC has been deprecated. So this issue is no longer prevalent.
