### ISSUE TITLE
Missing documentation for commands

### ISSUE THREAD

**Issue by nijahplays** [Vanilla-OS/vanilla-control-center#115]
There is no documentation for the `podman rm <container>` command or info in the apx man page

**Comment by kbdharun** [comment]
Thanks for the report, I will add the docs part to the to-do list.

**Comment by kbdharun** [comment]
Hi, the ability to remove subsystems (containers) has been added to Apx GUI (Separate documentation won't be needed), I am planning to work on a help page for it soon, closing this issue as completed.

**Comment by nijahplays** [comment]
Thanks!
