### ISSUE TITLE
Program fails to start properly if user has exported from named ubuntu container

### ISSUE THREAD

**Issue by dacwatson** [Vanilla-OS/vanilla-control-center#158]
### **Problem**
From a user-facing perspective, the program first hangs and fails to start, then subsequent attempts will start the program without content:
![image](https://github.com/Vanilla-OS/vanilla-control-center/assets/70728355/e9005da9-dbf0-4319-9739-35bac713f37d)

### **Cause**
Launching from terminal with the problematic export gives the following error:
```
user@vanilla ~> vanilla-control-center
/usr/share/vanilla-control-center/vanilla_control_center/dialog_installation.py:20: PyGIWarning: Vte was imported without specifying a version first. Use gi.require_version('Vte', '3.91') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gio, Gdk, GLib, Adw, Vte, Pango
INFO:Vanilla::Apx:Terminal: false
Traceback (most recent call last):
  File "/usr/share/vanilla-control-center/vanilla_control_center/main.py", line 90, in do_activate
    win = VanillaWindow(application=self)
  File "/usr/share/vanilla-control-center/vanilla_control_center/window.py", line 63, in __init__
    self.apx = Apx()
  File "/usr/share/vanilla-control-center/vanilla_control_center/backends/apx.py", line 65, in __init__
    self.__apps = self.__get_apps()
  File "/usr/share/vanilla-control-center/vanilla_control_center/backends/apx.py", line 106, in __get_apps
    "Container": self.__managed_containers[container]["Name"],
KeyError: 'apx_managed_dev'
``` 
I'm not fluent in python but my best guess is that there's some sort of problem with the dictionary when reading .desktops from custom named containers.

### Workaround

The best workaround I could find was to simply remove the offending desktop files or to change the extension to .txt in anticipation of a fix. After doing this the GUI launched flawlessly. 

I did notice that it still didn't detect my named container `apx_managed_dev` as you can see below: 

![image](https://github.com/Vanilla-OS/vanilla-control-center/assets/70728355/4ccbc014-21d3-4cc5-bdd7-ce783355c0f8)

I tried installing and exporting some programs on the default container and vanilla-control-center was still able to launch properly, so it's apparent the issue is with the custom named container.

**Comment by kbdharun** [comment]
Hi, this issue is longer prevalent with Subsystems in Apx GUI so I am closing this as completed.
