### ISSUE TITLE
Not installing Nvidia Drivers. (Not fixed)

### ISSUE THREAD

**Issue by MiMillieuh** [Vanilla-OS/vanilla-control-center#28]
When I choose a driver from the list it say installing and end in a few seconds prompting for a reboot but nothing has been done in the background.

(Also please Nvidia-520 support)

**Comment by mirkobrombin** [comment]
Please provide the output of `almost --version`

**Comment by MiMillieuh** [comment]
`mimillie@VanillaOS:~$ almost --version`
`almost version 1.2.7`

**Comment by mirkobrombin** [comment]
this at the time of the fail or after an upgrade/update?

**Comment by MiMillieuh** [comment]
> this at the time of the fail or after an upgrade/update?

Well it fails before and after updating the os.

But the welcome setup install properly the driver. It's juste impossible to change it that way.

And it's kinda annoying since my laptop is recent and need the 6.0 kernel to have the keyboard working. So my solution for now is to :

install the os
let the welcome setup untouched
Install Ubuntu mainline kernel.
Install the 6.0.x kernel
Reboot
Then go with the welcome setup.

**Comment by mirkobrombin** [comment]
Mh ok. We have plans to ship Vanilla with latest kernel, also kernel 6.0.1 is already in the vanilla repo

**Comment by MiMillieuh** [comment]
That's sweet, 
Let's hope the driver installer will work again soon then. also do you have plan to use the PPA for graphic drivers ? `(ppa:graphics-drivers/ppa)`
So that way the latest Nvidia Driver would be shiped.

**Comment by mirkobrombin** [comment]
I'll evaluate
