### ISSUE TITLE
Implement ABRoot tab

### ISSUE THREAD

**Issue by mrvladus** [Vanilla-OS/vanilla-control-center#69]

**Comment by mirkobrombin** [comment]
What ABRoot features would you like to manage from the control center?

**Comment by mrvladus** [comment]
- See present partition state maybe on top of the page
- Execute command (input field with execute button and output in Vte widget)
- Enter a shell button (open in terminal or in Vte widget on the same page)

**Comment by kbdharun** [comment]
Closing this issue, as VCC is deprecated and ABRoot shell is no longer present with Orchid (you can work with these programs in the systemd container which will be bundled with vso, to make changes to base [i.e pass commands] you can create your own images with VIB and rebase to it)
