### ISSUE TITLE
Proposal: Add Tasks tab to create and manage automated tasks from VSO

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/vanilla-control-center#74]
I would like to propose adding a Tab to Vanilla Control Center as a front end for VSO tasks. Also, we could show some preconfigured automated task examples similar to the Mac OS Shortcuts application. It will be a really cool feature to add.

**Comment by mirkobrombin** [comment]
I am already working on a dedicated app 

![image](https://user-images.githubusercontent.com/9479903/210847633-7dcf3de3-faeb-4bb6-86d7-c9d7c4b9ffc9.png)

**Comment by kbdharun** [comment]
> I am already working on a dedicated app
> 

Nice 😄
