### ISSUE TITLE
[Feature] A option to trigger update now

### ISSUE THREAD

**Issue by Heus-Sueh** [Vanilla-OS/vanilla-control-center#76]
maybe a button at the top of the list or below 
![Screenshot from 2023-01-07 13-13-01](https://user-images.githubusercontent.com/98482469/211160565-65621476-e3ad-4311-a822-f42e8a5e7148.png)

**Comment by ghost** [comment]
it seems like they added this
![image](https://user-images.githubusercontent.com/122128828/213952092-34b92a63-94e5-4f6e-988c-f411011c584e.png)
