### ISSUE TITLE
Add option to reset containers or delete

### ISSUE THREAD

**Issue by nonetrix** [Vanilla-OS/vanilla-control-center#90]
If I where to somehow break a container to where it's unusable or just want a clean start I should be able to reset it easily without having to use podman on the command line

Ideally should heavily warn the user before doing this to prevent mistakes

**Comment by ghost** [comment]
> 

Initializing the container won't wipe and delete all the data?

**Comment by kbdharun** [comment]
> > 
> 
> Initializing the container won't wipe and delete all the data?

Yes it will. That's why in Discord people were suggesting something like a confirmation box with a warning to confirm the deletion/reinitialization if this button is added.

**Comment by ghost** [comment]
> > > 
> > 
> > 
> > Initializing the container won't wipe and delete all the data?
> 
> Yes it will. That's why in Discord people were suggesting something like a confirmation box with a warning to confirm the deletion/reinitialization if this button is added.

+1 for my vote, then more GUI helps people learn

**Comment by mirkobrombin** [comment]
Closing since the vanilla control center will be deprecated in favor of the Apx GUI and reset/delete containers is a planned feature: https://github.com/Vanilla-OS/apx-gui/issues/1
