### ISSUE TITLE
Updates are available despite being just updated

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/vanilla-control-center#98]
Control center constantly says updates are available, even after updating the system. I'm not sure if this is a bug or if there are actually updates ready to be installed. Or if this is a feature to overwrite the system.

**Comment by mirkobrombin** [comment]
There was a problem in VSO which is fixed now. Fully upgrade your system via ABRoot and post here if the problem persist: 

```bash
sudo abroot shell
apt update
apt upgrade
exit
```

**Comment by ghost** [comment]
> There was a problem in VSO which is fixed now. Fully upgrade your system via ABRoot and post here if the problem persist:
> 
> ```shell
> sudo abroot shell
> apt update
> apt upgrade
> exit
> ```

Will do

**Comment by ghost** [comment]
> There was a problem in VSO which is fixed now. Fully upgrade your system via ABRoot and post here if the problem persist:
> 
> ```shell
> sudo abroot shell
> apt update
> apt upgrade
> exit
> ```

software store still displays this,
![image](https://user-images.githubusercontent.com/122128828/214040352-2273c3fa-3201-4c9f-91a0-ad44284d0f7b.png)

I'm guessing there are no updates available, but it would be nice if there was a message showing no updates available or your system to fully up to date

**Comment by ghost** [comment]
Same here. I see that updates are available after updating.
And this was done a clean install done a few hours earlier. Followed the steps mentioned in this issue, though it does not fix it.

**Comment by mirkobrombin** [comment]
There is probably something going wrong under the hood. I'll take a look.

**Comment by kbdharun** [comment]
> There is probably something going wrong under the hood. I'll take a look.

Yeah, I have the same issue too.

**Comment by GabsEdits** [comment]
Yeah, there is one more thing in this bug: The Control Center tells me an update, I click update. And does nothing and I tells me to restart, After I restart I see the same package that had to be updated:
[Screencast from 2023-01-29 13-16-43.webm](https://user-images.githubusercontent.com/110247388/215323659-7c88a1cd-14ef-4271-8abc-6490baef6614.webm)
And after reboot:
[Screencast from 2023-01-29 13-20-36.webm](https://user-images.githubusercontent.com/110247388/215323671-3766ca0d-4dc3-4515-a259-528087179fe7.webm)
